### ISSUE TITLE
Automatically use checksum from the online SHA256SUMS file

### ISSUE THREAD

**Issue by shaohua-deng** [andrewrothstein/ansible-terraform#10]
Each time there is an new version, must manually update the terraform_checksums variables.

I have an idea on how to automatically retrieve the checksum from the online SHA256SUMS file. It only depends commands grep and cut, something like below:
```yaml
   - name: Download SHA256SUMS file
      get_url:
        url: '{{ terraform_checksums_url }}'
        dest: /tmp/{{ terraform_checksums_file }}

    - name: get the checksum from file
      shell: "fgrep {{ terraform_zip }} /tmp/{{ terraform_checksums_file }} | cut -d ' ' -f 1"
      register: terraform_checksum

    - name: download terraform...
      become: yes
      become_user: root
      get_url:
        url: '{{ terraform_url }}'
        dest: /tmp/{{ terraform_zip }}
        checksum: '{{ terraform_checksum.stdout }}'
```
If it's good, I can make a pull request later.

**Comment by shaohua-deng** [comment]
oh, I realized grep and cut don't exist on Window, which is support by this ansible role.  It must be pure ansible, no dependency on shell or command line.

**Comment by shaohua-deng** [comment]
I found the pure ansible solution with some tricks of lookup() and regex_search()

test.yml
```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_ver: '0.12.0'
    terraform_platform: linux_amd64
    terraform_name: 'terraform_{{ terraform_ver }}'
    terraform_zip: '{{ terraform_name }}_{{ terraform_platform }}.zip'
    terraform_name: 'terraform_{{ terraform_ver }}'
    terraform_checksums_file: '/tmp/terraform_{{ terraform_ver }}_SHA256SUMS'
    pattern: '[0-9a-f]{64}  {{ terraform_zip }}'
  tasks:
    - name: find line in file
      set_fact:
        aaa: "{{lookup('file', terraform_checksums_file) | regex_search(pattern)}}"
    - name: returns list only 1 item - regex with group 
      set_fact:
        bbb: "{{lookup('file', terraform_checksums_file)| regex_search(pattern, '\\1')}}"
    - name: find the checksum from line
      set_fact:
        ccc: "{{(lookup('file', terraform_checksums_file)| regex_search(pattern)) [0:64] }}"
```

Run it will get result below, variable ccc is the checksum expected.  
```
$ ansible-playbook -v test.yml

TASK [find line in file] ********************************************************************************************
ok: [localhost] => {"ansible_facts": {"aaa": "42ffd2db97853d5249621d071f4babeed8f5fdba40e3685e6c1013b9b7b25830  terraform_0.12.0_linux_amd64.zip"}, "changed": false}

TASK [return list only 1 item - regex with group] *******************************************************************
ok: [localhost] => {"ansible_facts": {"bbb": ["42ffd2db97853d5249621d071f4babeed8f5fdba40e3685e6c1013b9b7b25830"]}, "changed": false}

TASK [cut the checksum from line] ***********************************************************************************
ok: [localhost] => {"ansible_facts": {"ccc": "42ffd2db97853d5249621d071f4babeed8f5fdba40e3685e6c1013b9b7b25830"}, "changed": false}
```

**Comment by andrewrothstein** [comment]
Thanks for investigating this option. I'm okay with a slight bit of manual effort around new versions. The benefit we derive from memorializing the checksums in the role is that we can hold Hashicorp accountable for not changing the released versions of their code.

**Comment by andrewrothstein** [comment]
Being able to see the checksums for a particular version is a problem I've tended to solve with bash + curl. An ansible native solution would be excellent to have as well.

**Comment by andrewrothstein** [comment]
Do you think this functionality is better developed as a role or some other Ansible component?

**Comment by shaohua-deng** [comment]
The best I could think about is that get_url can handle the checksum file directly.  Let me assume two more parameters:
```
checksum_url:  the same format as url parameter, but points to the checksum file. 
checksum_algorithm: md5, sha256 etc
```
The checksum file might contain multiple checksums, so get_url should be able find the right one by the file name at the end of the each line
```
<checksum> <filename>
```
The *sum commands (sha256sum, md5sum etc), can verify the checksum with -c option.
```
       -c, --check
              read MD5 sums from the FILEs and check them

$ sha256sum -c terraform_0.12.0_SHA256SUMS 
sha256sum: terraform_0.12.0_darwin_amd64.zip: No such file or directory
terraform_0.12.0_darwin_amd64.zip: FAILED open or read
terraform_0.12.0_linux_amd64.zip: OK
```

**Comment by shaohua-deng** [comment]
Obviously, I am not the first one has this idea, see 
https://github.com/ansible/ansible/issues/48790

The improvement is already included in ansible 2.8. It's also backported to 2.7, so the latest 2.7 minor version should work too.  This improvement just wasn't mentioned in the document.
https://github.com/ansible/ansible/pull/53685

I have verified that the code below works with ansible 2.8.0
```
    - name: download terraform...
      become: yes
      become_user: root
      get_url:
        url: '{{ terraform_url }}'
        dest: /tmp/{{ terraform_zip }}
        checksum: 'sha256:{{ terraform_checksums_url }}'

TASK [andrewrothstein.ansible-terraform : download terraform...] ***************************************************
changed: [localhost]

```
